name: Otus CI

on: [pr]

jobs
  build: 
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@3
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm lint
      - run: npm test